project_id = "biggyamzmxtwgowxqkdn"

[functions.generate-book]
verify_jwt = false

[functions.generate-book-v2]
verify_jwt = false

[functions.generate-chapter]
verify_jwt = false

[functions.generate-cover-image]
verify_jwt = false

[functions.fetch-local-resources]
verify_jwt = false

[functions.send-update-offer]
verify_jwt = false

[functions.generate-ebook-file]
verify_jwt = false

[functions.fetch-image-data-url]
verify_jwt = false
